# Site settings
title: Froggy Form
email: kailashraj@lftechnology.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lftechnology.com" # the base hostname & protocol for your site
twitter_username: FriedDust
github_username:  lf-kailashraj

# Build settings
markdown: kramdown
